resources:
  repositories:
  - repository: pipeline
    type: git
    name: easydevops
    ref: refs/heads/master

trigger:
  batch: true
  branches:
    include:
    - release-*
    - refs/tags/dev-release*
  paths:
    include:
    - src/services/categories/*
    exclude:
    - azure-pipelines.yml

pr: none

jobs:
- template: job-template-main.yml@pipeline
