---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: categories
  namespace: ${NAMESPACE}
spec:
  replicas: ${NUM_REPLICAS}
  template:
    metadata:
      labels:
        app: categories
      name: categories
    spec:
      imagePullSecrets:
      - name: ${REGSECRET}
      containers:
      - name: categories
        image: ${BUILD_IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
          name: service-port
        env:
        - name: ENV_NAME
          value: "${DOCKER_TARGETS}"
        - name: MONGO_HOST
          value: "${MONGO_HOST}"
        - name: MONGO_PORT
          value: "${MONGO_PORT}"
        - name: MONGO_NAME
          value: "${CATEGORIES_MONGO_NAME}"
        - name: MONGO_PASSWORD
          value: "${MONGO_PASSWORD}"
        - name: MONGO_USER
          value: "${MONGO_USER}"
---
