---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: categories
  name: categories
  namespace: learnbytesting
spec:
  ports:
  - name: categories
    port: 80
    targetPort: service-port
    protocol: TCP
  selector:
    app: categories
---
